### PR TITLE
Feature/wplug 124 - Teaser Multiline Support

### PR DESCRIPTION
**Pull request by Antaru**
Simply preserve whitespace in `<text>`-element when multiline option is configured.

Multiline is only allowed for field with id `"text"`

### CODE REVIEW

**Comment by dotvoid** [comment]
We need to explicitly use idf format, and use the "element" sub element for each line. Also we need to support transformation when opening/importing single line text when the plugin has been configured as multiline and vice versa.

```
<text format="idf">
     <element id="paragraph-0e8a416f24d99f0008a6facac9a3976e" type="body">one line</element>
     <element id="paragraph-fa79bca8a416fd9f836facab9a3935bd" type="body">second line</element>
<text/>
```
This needs to be documented in the readme as enabling multiline has an effect on the website layer.

**Comment by Antaru** [comment]
Multiline support using `<text format="idf" />` is now implemented. When it's enabled the text will be stored as TextNodes in the TeaserNode.nodes-property, otherwise it's stored as a string in the TeaserNode.text-property.

**Multiline Enabled**
When opening an article saved without `format="idf"`, the converter will insert a TextNode in the array TeaserNode.nodes and enable further editing.
When opening an article saved with `format="idf"`, the converter will convert the child-elements to TextNodes.

**Multiline Disabled**
When opening an article saved with `format="idf"`, the converter will flatten the child-elements into a single string and store it in TeaserNode.text. Annotations are preserved.
When opening an article saved without `format="idf"`, the converter will get the value in the `<text/>`-element and store it in the TeaserNode.text-property. This is the standard behavior.

When saving an article it will be stored correctly according to the multiline-config value.

**Comment by dotvoid** [comment]
When adding a new teaser with a multiline text field in the first/default teaser, the field disappears. Works when adding a new teaser type in an already added/existing teaser.

**Comment by Antaru** [comment]
@dotvoid Initial node when creating teaser should now be added correctly.

**Comment by Antaru** [comment]
Behöver fortfarande kollas över:
* Teaser sparad utan `<text>`-element i `<data>` får ingen tom text-nod när den importeras och multiline är aktiverad.
* Text-noden som skapas när en teaser med text öppnas i writer efter att multiline har aktiverats får id i stil med `paragraph-1`, den bör genereras bättre. Se: `plugins/se.infomaker.ximteaser/TeaserConverter.js:129`

**Pull request merged**
